server:
 servlet:
  context-path: /pessoa-endereco/api
 port: ${SERVER_PORT:8082}
  
spring:
 datasource:
  url: jdbc:h2:mem:demodb
  username: sa
  password:
  driverClassName: org.h2.Driver
    
 h2:
     console:
      enabled: true
      path: /h2-console